name: herbal_gallary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  font_awesome_flutter: ^10.10.0
  flutter_tts: ^4.2.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png   # make sure your logo exists here

# â† flutter_icons MUST be outside 'flutter'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

